# normally this file should not be pushed to git
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque # applications have to know how to decode the data
# for the field "data" I would have to use base64 encoded strings
stringData:
  PLACEHOLDER: nothing
