apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  replicas: 2
  selector:
    # so the deployment knows which pods to manage (see definition of the label in the pod definition [= template])
    matchLabels:
      app: auth
  strategy:
    # replace the old pods with the new ones
    type: RollingUpdate
    rollingUpdate:
      # the aim is to have 2 pods (see above)
      # when replacing the old pods it could be necessary to have 3 pods for a short time
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      # limits for ressources are missing for now
      containers:
        - name: auth
          image: mhouney/file_converter_auth:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret